controller_list:
  - name: fake_manipulator_controller
    joints:
      - atrvjr/shoulder_pan_joint
      - atrvjr/shoulder_lift_joint
      - atrvjr/elbow_joint
      - atrvjr/wrist_1_joint
      - atrvjr/wrist_2_joint
      - atrvjr/wrist_3_joint