outdoors_topic:       /odometry/filtered
indoors_topic:        /amcl_pose
control_topic:        /switch_to
pub_topic:            /final_pose
amcl_enable_tf_param: /amcl/tf_broadcast
origin_x:             0.0
origin_y:             0.0
origin_yaw:           0.0